version: 2.1

orbs:
  android: circleci/android@1.0.3
jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleDebug
      - run:
          name: install jq
          command: |
            wget http://stedolan.github.io/jq/download/linux64/jq
            chmod +x ./jq

      - run:
          name: Generate Kobiton URL
          command: |
            response=$(curl -X POST https://api.kobiton.com/v1/apps/uploadUrl -H 'Authorization: Basic a3Vua2E4MjcxQGdtYWlsLmNvbTo1ZGM2Njk5NS0yMjMxLTQyZjktYjBhYS1iNjk3OTMzZTMwNDI=' -H 'Content-Type: application/json' -H 'Accept: application/json' --data '{"filename":"app-debug.apk","appId":282134}')
            url=$(echo $response | ./jq '.url')
            appPath=$(echo $response | ./jq '.appPath')
            appPath=$(echo {\"appPath\":$appPath})
            url=${url%\"}
            url=${url#\"}
            curl -T "app/build/outputs/apk/debug/app-debug.apk"  -H "Content-Type: application/octet-stream" -H "x-amz-tagging: unsaved=true" -X PUT $url
            curl -X POST https://api.kobiton.com/v1/apps -H 'Authorization: Basic a3Vua2E4MjcxQGdtYWlsLmNvbTo1ZGM2Njk5NS0yMjMxLTQyZjktYjBhYS1iNjk3OTMzZTMwNDI=' -H 'Content-Type: application/json' -H 'Accept: application/json' -d $appPath

      - store_artifacts:
          path: app/build/outputs/apk
          destination: artifact-file
workflows:
  android-build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
