version: 2.1

orbs:
  android: circleci/android@1.0.3
jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleDebug
workflows:
  android-build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
